### ISSUE TITLE
No file was downloaded + errors

### ISSUE THREAD

**Issue by mmupmip** [rayokamoto/AUDIT#12]
On Chrome: 
![image](https://github.com/rayokamoto/AUDIT/assets/161221547/62e88e2d-9b1b-4bbf-b09f-5b000b37abf6)

On Firefox:
![image](https://github.com/rayokamoto/AUDIT/assets/161221547/34574147-d7c5-44d1-ac92-d122702bc176)

**Comment by rayokamoto** [comment]
Chrome is a known issue that is yet to be fixed so we will need to look into that. For Firefox, have you ensured that you have give the addon/extension the correct permissions? Otherwise, the extension cannot use the API due to insufficient privileges.

**Comment by mmupmip** [comment]
You're right that I did not give all permissions, however, after I did, it just stayed like this for >5mins. Is it suppose to be a long download?

![image](https://github.com/rayokamoto/AUDIT/assets/161221547/f64aabf8-6cbb-4ccf-b6c6-611af69e9159)

**Comment by rayokamoto** [comment]
It should be basically instant, although it works for me so it's rather peculiar...

@rishiad thoughts?

**Comment by mmupmip** [comment]
Firefox version 123.0 on my MSI laptop.
![image](https://github.com/rayokamoto/AUDIT/assets/161221547/409aa8a2-8b3f-4892-9248-e46a24d33c10)

**Comment by rayokamoto** [comment]
[v1.3.0](https://github.com/rayokamoto/AUDIT/releases/tag/v1.3.0) was released with some fixes, I wonder if this fixes things?

**Comment by mmupmip** [comment]
I forgot about this lol, but it works now. Thanks!
