### ISSUE TITLE
Incorrect file type for Outlook & Apple Calendar

### ISSUE THREAD

**Issue by traunts** [rayokamoto/AUDIT#6]
The extension creates a `.ical` file containing the student timetable, but current Apple Calendar and Outlook versions only accept a `.ics` file when importing. 

Tested on Apple Calendar Version 11.0 and Outlook web-app.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/73866773/230047507-71833d6e-429a-4189-aa63-842ea7bc5d3b.png">

<img width="967" alt="Screen Shot 2023-04-05 at 7 28 37 pm" src="https://user-images.githubusercontent.com/73866773/230048424-5bb9f509-39d7-4404-8094-4eb4e185eebc.png">

Google Calendars accept either file type. 

### Recommended fix:
Update the `README.md` to specify this requirement, or change the output file extension to `.ics` / support `.ics` saving.

**Comment by rayokamoto** [comment]
Hey, thanks for raising the issue!

The issue has been fixed in commit dee1fef3565ef48440fdd1bec9d9570b456ed90c and files are now downloaded as a `.ics` file rather than `.ical` for compatibility.

**Comment by rayokamoto** [comment]
v1.1.0 which has the fix has now been shipped. It can be viewed [here](https://github.com/rayokamoto/AUDIT/releases/tag/v1.1.0).
